### ISSUE TITLE
Build Shelf

### ISSUE THREAD

**Issue by bugzy** [Atem18/mauikit-fedora#1]
Any chance you can add Shelf to the builds?
https://invent.kde.org/maui/shelf

**Comment by Atem18** [comment]
@bugzy Yes, let me try it.

**Comment by Atem18** [comment]
@bugzy It's working as you can see : https://copr.fedorainfracloud.org/coprs/atem18/MauiKit/package/shelf/

If you already enabled my copr, you just need to do : dnf install shelf

Enjoy :)

**Comment by bugzy** [comment]
Thanks

**Comment by Atem18** [comment]
@bugzy Np
